export const DASHBOARD_NAME = 'dashboard'
export const USER_PREMISSION_NAME = 'user-accordion'
export const USER_GROUP_MANAGEMENT_NAME = 'user-group'
export const USER_MANAGEMENT_NAME = 'user-management'
export const PERMISSION_MANAGEMENT_NAME = 'user-permission'
