### GET request to example server
GET https://nasafa-plus-api.test:8443/api/home

###


### POST request to example server for login
POST https://nasafa-plus-api.test:8443/api/login/
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "admin123"
}

###